### ISSUE TITLE
Where is pdf-avy-highlight demo?

### ISSUE THREAD

**Issue by phye** [dalanicolai/dala-emacs-lisp#3]
In your readme you've mentioned 'demo below', but I just cannot find it :)

**Comment by dalanicolai** [comment]
Demo is referring to that .gif (screencast) that should be shown just below that line. If it is not showing, then I guess you should check your browser settings (it is working fine here).

If maybe you expected some tutorial, then indeed that is missing. However, you could just load the [pdf-avy-highlight.el](https://github.com/dalanicolai/dala-emacs-lisp/blob/master/pdf-avy-highlight.el) file, then open some pdf with pd-tools, en do `M-x pdf-keyboard-highlight`. Then type some starting pattern, choose label, type some ending pattern and choose again a label... that's it. Although the keyboard highlighting works fine, as I mentioned there already, maybe sometimes it is not such bad idea to use the mouse. Also, there are better ways to implement keyboard highliting, like in [djvu3](https://github.com/dalanicolai/djvu3).
Maybe one day I will implement that mechanism, including preview, into the [doc-tools](https://github.com/dalanicolai/doc-tools) package.

**Comment by phye** [comment]
Indeed there're something wrong with my chrome days ago... I can find the demo now.

I understand that it's a bit complex to select begin and end word using avy, and using mouse to select region may be quicker. But I really don't like the 'switch of context' when selecting some region using mouse, then switch to some complex keybindings to annotate or highlight...

That said, given the complexity of drafter version of region selection using avy, it's still valuable for me, and maybe valuable for others. How about enhance it to benifit more people? (using keyboard to select region in pdf-tools is by far the most appealing feature for me, even more appealing than continuous scrolling!)

Looking forward to your doc-tools and thanks for the great idea!

**Comment by dalanicolai** [comment]
About the context switching, I was thinking that you could of course bind the `pdf-annot-add-highlight-markup-annotation` function to some mouse button/click that you otherwise don't use.

**Comment by phye** [comment]
That's true.
But as an orgmode user, normally I will split another window to write down some notes. I cannot bind mouse to write anything, so...

In addition, maybe your current keybindings are a bit complicated, how about just use avy to select the first place to start selecting, and using vim motion(such as w for  current word, e for the end of word?) to select region? 

Be it evil like, and I'm sure it will be quite popular. In fact, that's actually my dream pdf tool, far better than zathura, ocular, macOS preview .etc

**Comment by dalanicolai** [comment]
Your idea sounds good, but unfortunately, with the current pdf-tools server API, this would be very cumbersome to implement. However, this would be quite easy in the doc-tools package, where I have already implemented an 'experimental' cursor navigation feature. But unfortunately I do not have much time to work on that package, so that it probably will take a while before I can work on implementing this...

**Comment by phye** [comment]
Thanks for the explanation!
It's not an emergent request, and I can wait until you have spare time (or if I learned elisp to do it by myself :))
