### ISSUE TITLE
`pdf-annot-add-markup-annotation` is missing

### ISSUE THREAD

**Issue by nameiwillforget** [dalanicolai/dala-emacs-lisp#4]
Hello! I wanted to use your `pdf-avy-highlight`-package, but when I try to it says that `pdf-annot-add-markup-annotation` is missing. A quick search through your repository only found `pdf-annot-add-markup-annotation` mentioned in the definition of `pdf-keyboard-highlight`. Where do I get that command from? My Emacs version is 30.0.5. Also, the command `pdf-keyboard-highlight` in `pdf-avy-highlight.el` is named the same as a command in `pdf-keyboard-highlight.el`. I tried to use that command too but got the similar error message

```
let: Symbol’s function definition is void: pdf-annot-add-highlight-markup-annotation
```

**Comment by dalanicolai** [comment]
Thanks for your message. This function is part of pdf-tools and can be found in its pdf-annot package (hence the function uses/starts with the pdf-annot namespace). Indeed, the `require` was missing  from the package, I have included it now.
